# basic options, i can say what ever here
title: New-awesome-blog
author: Smart Guy
email: your-email@domain.com
description: A lovely wonderful blog
twitter_username: Ulysses
github_username: Ulysses3k

# Build settings
markdown: kramdown
theme: minima
